name: isolate_supervisor

version: 1.0.2
homepage: https://github.com/nxtSwitch/isolate_supervisor
repository: https://github.com/nxtSwitch/isolate_supervisor
description: This library constructs higher-level isolate interfaces on top of the lower level dart:isolate library.

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  test: ^1.14.6
  pedantic: ^1.9.0
