name: isolate_supervisor

version: 1.0.1
repository: https://github.com/nxtSwitch/isolate_supervisor
description: A library for easy concurrency with isolates.

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  test: ^1.6.0
  pedantic: ^1.8.0