name: isolate_supervisor

version: 1.0.1
homepage: https://github.com/nxtSwitch/isolate_supervisor
repository: https://github.com/nxtSwitch/isolate_supervisor
description: This library constructs higher-level isolate interfaces on top of the lower level dart:isolate library.

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  test: ^1.6.0
  pedantic: ^1.8.0