name: isolate_supervisor

version: 1.0.0
repository: https://github.com/nxtSwitch/isolate_supervisor
description: A starting point for Dart libraries or applications.


environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
